version: 3

tasks:
  clean:
    desc: Clean
    cmds:
      - rm -rf dist

  install:
    cmds:
      - go mod download
      - go mod tidy

  build:
    desc: Build
    cmds:
      - goreleaser --snapshot --clean

  dependencyUpdates:
    desc: Show dependency updates
    deps: [ install ]
    cmds:
      - go list -u -m -json all | go-mod-outdated -update -direct
