version: 3

tasks:
  clean:
    desc: Clean
    cmds:
      - rm -rf dist

  install:
    cmds:
      - go mod download
      - go mod tidy

  build:
    desc: Build
    deps: [ install ]
    cmds:
      - mkdir -p build
      - go build -o build/ .

  dependencyUpdates:
    desc: Show dependency updates
    deps: [ install ]
    cmds:
      - go list -u -m -json all | go-mod-outdated -update -direct
